Ports "Wheeler" hairstyle
HearthOfHestia/Nebula pull request #150
Opened 2021-10-31 19:06 UTC by Cupax3

please I ***need*** this

## Description of changes
Ports the Wheeler hairstyle from Bay

## Why and what will this PR improve
Please I need this hairstyle it's essential to my being

## Authorship
Monimus ported them to Bay from Aurora, original author on Aurora is Wraithcraft

## Changelog

:cl: Wraithcraft, Monimus
imageadd: Adds Wheeler hairstyle from Aurora/Bay
/:cl:

2021-11-04 20:57 UTC, MarinaGryphon requested changes
~~okay so for what it's worth the character it was added for wasn't a dude~~

2021-11-04 20:57 UTC, MarinaGryphon commented on code/modules/sprite_accessories/_accessory_hair.dm
> +	gender = MALE
```suggestion
```

2021-11-05 00:09 UTC, Cupax3 commented on code/modules/sprite_accessories/_accessory_hair.dm
> +	gender = MALE
🆗

2021-11-05 13:25 UTC, MarinaGryphon approved these changes

2021-11-05 21:08 UTC, merged