Medbay Fix 2
HearthOfHestia/Nebula pull request #89
Opened 2021-09-27 03:52 UTC by DeadmonWonderland

## Description of changes

Adds a proper tag in the scanner displays so they will now push to the body scan displays. Also gets rid of display that was causing some wierd fuckery.  Also removes a part of a table.

## Why and what will this PR improve

Fixes a bug. Fixes some wierd fuckery with displays, and slight housekeeping.

## Authorship

me

## Changelog

:cl: Deadmon
bugfix: Scans now push to the displays.
rscdel: Removes the display that was overlayed on another, resulting in some fuckery when you looked at it from the side.
/:cl:

2021-09-27 05:44 UTC, Andromeda-K22 commented
fails CI because you use tag and not id_tag

2021-09-30 21:13 UTC, MarinaGryphon commented
PR is nonfunctional, the wrong variable was used.

2021-10-02 15:20 UTC, MarinaGryphon requested changes
CI fixes.

2021-10-02 15:20 UTC, MarinaGryphon commented on maps/torch/torch5_deck1.dmm
> +	tag = "scanner_or"
```suggestion
	id_tag = "scanner_or"
```

2021-10-02 15:20 UTC, MarinaGryphon commented on maps/torch/torch5_deck1.dmm
> +	tag = "scanner_or"
```suggestion
	id_tag = "scanner_or"
```

2021-10-02 15:20 UTC, MarinaGryphon commented on maps/torch/torch5_deck1.dmm
> +	tag = "scanner_or"
```suggestion
	id_tag = "scanner_or"
```

2021-10-02 15:41 UTC, MarinaGryphon approved these changes

2021-10-02 15:45 UTC, merged